public class _5_loops_and_arrays {
    public static void main(String[] args) {
        int i= 1;
        System.out.println("in for loop, initialsiation, condition, updation arguments are optional");
        for(;i<=3;i++){
            System.out.println("For loop without initilisation");
        }
        i= 1;
        for(System.out.println("We can even print in intilsiation part");i<=3;i++){
            System.out.println(i);
        }
        
        i = 1;
        for(;i<=3;){
            System.out.println("Print without initlsiation and updation in the for loop statement");
            i+=1;
        }







        for(int a = 0, b = 1;a<=3 && b<=3;a++,b++){
            System.out.println("We can have multiple initialisation and updations in the for loop.");
        }

        i = 1;
        for(;;){
            System.out.println("Print without initlsiation,condition and updation in the for loop statement, it executes forever.So,ill break here voluntarily");
            break;
        }

        System.out.println("Acc., to Java, an object is a class instance or an array. Arrays are ");
        int A[] = {1,2,3,4,5};
        int B[] = new int[5];
        int C[][] = {{1,2,3,4,5},{6,7,8,9,10}};
        int D[][] = new int[2][5];

        System.out.println("Unlike strings, in java, whether u use new keyword or initialise the values directly, arrays are always stored in heap. The reason is arrays can change their content, arrays are mutable objects, whereas strings are immutable. So, arrays with identical values are still considered distinct objects and didnt have any string pool kind of opitimisation thing like strings had.");

        System.out.println("length is a final variable (field) of the array object, not a method. You access it as array.length without parentheses, whereas ins tring, lenght is a method of string class string.length() ");
        for(int x: A){
            System.out.println("Im in for-each loop "+x);
        }
        
        System.out.println("Jagged or Ragged array is array of arrays such that member arrays can be of different sizes. Check it below");
        int K[][];
        K = new int[3][];
        K[0] = new int[3];
        K[1] = new int[2];
        K[2] = new int[1];

        System.out.println("We can create arrays with [] both before , after, adn in both sides to teh ref var., All r valid. Check it below");
        int [][] L;
        int M[][];
        int []N[];

        int [] O, P[];
        O = new int[5];
        P = new int[5][5];

        System.out.println("In Java, arrays are a special kind of object, they r not a primitive type, but they are also not instances of a regular class like other objects. Arrays are dynamically created objects that inherit from Object class. Unlike normal classes (e.g., String, ArrayList), arrays do not have a class definition in Java source code. The JVM creates array types dynamically at runtime. The .class syntax works for arrays (e.g., int[].class, String[].class), but these are synthetic types generated by the JVM. All array types implicitly extend Object class. They also implement Cloneable and java.io.Serializable. So, while they act like objects, they are a unique construct in Java, different from both primitives and normal class instances.");

    }
}


