spring.application.name=springBoot
server.port=8999
dep3.about = I'm dependency 3, from application.properties, Even though the field is public, Spring Boot doesn't access it directly. Instead, it uses a JavaBeans binding mechanism, which requires Private fields or Public getters and setters. This is by design. Spring uses reflection via setters, not direct field access.

spring.datasource.url=jdbc:postgresql://localhost:5432/mydb
spring.datasource.username=postgres
spring.datasource.password=postgres
