package com.vishal.JPAHibernate.Controllers;

import com.vishal.JPAHibernate.DTO.BookDTO;
import com.vishal.JPAHibernate.DTO.BookResponseDTO;
import com.vishal.JPAHibernate.Entities.Book;
import com.vishal.JPAHibernate.mappers.BookMapper;
import com.vishal.JPAHibernate.services.BookService;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import java.util.List;

@RestController
public class BookController {

    private final BookService bookService;
    private final BookMapper bookMapper;



    public BookController(BookService bookService, BookMapper bookMapper) {
        this.bookService = bookService;
        this.bookMapper = bookMapper;
    }

    /**
     * Use POST to create a new resource (server assigns the URI) e.g in our author db instance creation endpoint, we didn't mention the author_id, when we send request from Postman i.e Client-side, its automatically generated by the db - auto-generated. Use PUT to create or fully replace a resource at a client-specified URI. A PUT request is considered idempotent. This means that making multiple identical PUT requests will have the same effect on the server state as a single request. A POST request is generally not considered idempotent. If you send the same POST request multiple times, it result in the creation of multiple new resources or multiple changes to the server state. For example, repeatedly sending a POST request to create a new user create a new user record each time, resulting in duplicates.
     */
    @PutMapping(path = "/books/{isbn}")
    public ResponseEntity<BookResponseDTO> createOrUpdateBook(@PathVariable String isbn, @RequestBody BookDTO bookDTO) {
        bookDTO.setIsbn(isbn);
        Book retrievedBook = bookMapper.mapTo(bookDTO);
        Book savedBook = bookService.saveBook(retrievedBook);
        BookResponseDTO bookResponseDTO = bookMapper.mapBookEntitiyToResponse(savedBook);
        return new ResponseEntity<>(bookResponseDTO, HttpStatus.OK);
    }


    @GetMapping(path = "/books")
    public List<BookResponseDTO> listBooks(){
        List<Book> books = bookService.findAll();
        return books.stream().map(bookMapper::mapBookEntitiyToResponse).toList();
    }




}
